from PyQt6 import QtCore, QtGui, QtWidgets
from waysideclass import *

blueLine = WaysideController(1,True,True,True,1)

class UI_BlueLine(object):
    def setupUi(self, BlueLine):
        BlueLine.setObjectName("BlueLine")
        BlueLine.resize(777, 644)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        BlueLine.setFont(font)
        BlueLine.setStyleSheet("QWidget{\n"
"\n"
"background-color:#adadadad\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=BlueLine)
        self.centralwidget.setObjectName("centralwidget")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(350, 540, 171, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.Occupancy = QtWidgets.QLabel(parent=self.centralwidget)
        self.Occupancy.setGeometry(QtCore.QRect(320, 230, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Occupancy.setFont(font)
        self.Occupancy.setObjectName("Occupancy")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(40, 570, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_42 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(10, 11, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(100, 30, 91, 31))
        self.label_43.setObjectName("label_43")
        self.switchoutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.switchoutput.setGeometry(QtCore.QRect(560, 580, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.switchoutput.setFont(font)
        self.switchoutput.setObjectName("switchoutput")
        self.BlockTable_5 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.BlockTable_5.setGeometry(QtCore.QRect(20, 30, 701, 81))
        self.BlockTable_5.setObjectName("BlockTable_5")
        self.BlockTable_5.setColumnCount(10)
        self.BlockTable_5.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_5.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_5.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_5.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_5.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_5.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_5.setItem(1, 9, item)
        self.BlockTable_5.horizontalHeader().setDefaultSectionSize(67)
        self.BlockTable_5.horizontalHeader().setMinimumSectionSize(30)
        self.BlockTable_5.verticalHeader().setDefaultSectionSize(17)
        self.Authority = QtWidgets.QLabel(parent=self.centralwidget)
        self.Authority.setGeometry(QtCore.QRect(320, 110, 180, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.Authority.setFont(font)
        self.Authority.setObjectName("Authority")
        self.CommandedSpeed = QtWidgets.QLabel(parent=self.centralwidget)
        self.CommandedSpeed.setGeometry(QtCore.QRect(300, 0, 230, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.CommandedSpeed.setFont(font)
        self.CommandedSpeed.setObjectName("CommandedSpeed")
        self.SignalLights = QtWidgets.QLabel(parent=self.centralwidget)
        self.SignalLights.setGeometry(QtCore.QRect(320, 330, 170, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.SignalLights.setFont(font)
        self.SignalLights.setObjectName("SignalLights")
        self.SignalLights_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.SignalLights_2.setGeometry(QtCore.QRect(320, 440, 200, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.SignalLights_2.setFont(font)
        self.SignalLights_2.setObjectName("SignalLights_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 580, 140, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.BlockTable_8 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.BlockTable_8.setGeometry(QtCore.QRect(20, 140, 711, 91))
        self.BlockTable_8.setObjectName("BlockTable_8")
        self.BlockTable_8.setColumnCount(10)
        self.BlockTable_8.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_8.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_8.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_8.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_8.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_8.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_8.setItem(1, 9, item)
        self.BlockTable_8.horizontalHeader().setDefaultSectionSize(67)
        self.BlockTable_8.horizontalHeader().setMinimumSectionSize(30)
        self.BlockTable_8.verticalHeader().setDefaultSectionSize(17)
        self.BlockTable_9 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.BlockTable_9.setGeometry(QtCore.QRect(20, 260, 711, 81))
        self.BlockTable_9.setObjectName("BlockTable_9")
        self.BlockTable_9.setColumnCount(10)
        self.BlockTable_9.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_9.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_9.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_9.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_9.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_9.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_9.setItem(1, 9, item)
        self.BlockTable_9.horizontalHeader().setDefaultSectionSize(67)
        self.BlockTable_9.horizontalHeader().setMinimumSectionSize(30)
        self.BlockTable_9.verticalHeader().setDefaultSectionSize(17)
        self.BlockTable_10 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.BlockTable_10.setGeometry(QtCore.QRect(20, 360, 711, 81))
        self.BlockTable_10.setObjectName("BlockTable_10")
        self.BlockTable_10.setColumnCount(10)
        self.BlockTable_10.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_10.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_10.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_10.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_10.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_10.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_10.setItem(1, 9, item)
        self.BlockTable_10.horizontalHeader().setDefaultSectionSize(67)
        self.BlockTable_10.horizontalHeader().setMinimumSectionSize(30)
        self.BlockTable_10.verticalHeader().setDefaultSectionSize(17)
        self.BlockTable_11 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.BlockTable_11.setGeometry(QtCore.QRect(20, 470, 701, 81))
        self.BlockTable_11.setObjectName("BlockTable_11")
        self.BlockTable_11.setColumnCount(10)
        self.BlockTable_11.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_11.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BlockTable_11.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_11.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_11.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_11.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        item.setFont(font)
        self.BlockTable_11.setItem(1, 9, item)
        self.BlockTable_11.horizontalHeader().setDefaultSectionSize(67)
        self.BlockTable_11.horizontalHeader().setMinimumSectionSize(30)
        self.BlockTable_11.verticalHeader().setDefaultSectionSize(17)
        BlueLine.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=BlueLine)
        self.statusbar.setObjectName("statusbar")
        BlueLine.setStatusBar(self.statusbar)

        self.retranslateUi(BlueLine)
        QtCore.QMetaObject.connectSlotsByName(BlueLine)

    def retranslateUi(self, BlueLine):
        _translate = QtCore.QCoreApplication.translate
        BlueLine.setWindowTitle(_translate("BlueLine", "MainWindow"))
        self.label_9.setText(_translate("BlueLine", "        Switches\n"
"    (5 to 6 / 5 to 11)"))
        self.Occupancy.setText(_translate("BlueLine", "Occupancy"))
        self.label_12.setText(_translate("BlueLine", "Gate Status:"))
        self.label_42.setText(_translate("BlueLine", "Operational:"))

        if(blueLine.getTrackOperational()==True):
            self.label_43.setText(_translate("BlueLine", "Working"))
        else:
            self.label_43.setText(_translate("BlueLine", "Closed"))

        if blueLine.getswitchPositions() == True:
            self.switchoutput.setText(_translate("BlueLine", "5 to 6"))
        else:
            self.switchoutput.setText(_translate("BlueLine", "5 to 11"))

        item = self.BlockTable_5.verticalHeaderItem(1)
        item.setText(_translate("BlueLine", "1"))
        item = self.BlockTable_5.horizontalHeaderItem(0)
        item.setText(_translate("BlueLine", "0"))
        item = self.BlockTable_5.horizontalHeaderItem(1)
        item.setText(_translate("BlueLine", "1"))
        item = self.BlockTable_5.horizontalHeaderItem(2)
        item.setText(_translate("BlueLine", "2"))
        item = self.BlockTable_5.horizontalHeaderItem(3)
        item.setText(_translate("BlueLine", "3"))
        item = self.BlockTable_5.horizontalHeaderItem(4)
        item.setText(_translate("BlueLine", "4"))
        item = self.BlockTable_5.horizontalHeaderItem(5)
        item.setText(_translate("BlueLine", "5"))
        item = self.BlockTable_5.horizontalHeaderItem(6)
        item.setText(_translate("BlueLine", "6"))
        item = self.BlockTable_5.horizontalHeaderItem(7)
        item.setText(_translate("BlueLine", "7"))
        item = self.BlockTable_5.horizontalHeaderItem(8)
        item.setText(_translate("BlueLine", "8"))
        item = self.BlockTable_5.horizontalHeaderItem(9)
        item.setText(_translate("BlueLine", "9"))
        __sortingEnabled = self.BlockTable_5.isSortingEnabled()
        self.BlockTable_5.setSortingEnabled(False)
        item = self.BlockTable_5.item(0, 0)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_5.item(0, 1)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 1"))))
        item = self.BlockTable_5.item(0, 2)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 2"))))
        item = self.BlockTable_5.item(0, 3)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 3"))))
        item = self.BlockTable_5.item(0, 4)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 4"))))
        item = self.BlockTable_5.item(0, 5)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 5"))))
        item = self.BlockTable_5.item(0, 6)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 6"))))
        item = self.BlockTable_5.item(0, 7)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 7"))))
        item = self.BlockTable_5.item(0, 8)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 8"))))
        item = self.BlockTable_5.item(0, 9)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 9"))))
        item = self.BlockTable_5.item(1, 0)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 10"))))
        item = self.BlockTable_5.item(1, 1)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 11"))))
        item = self.BlockTable_5.item(1, 2)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 12"))))
        item = self.BlockTable_5.item(1, 3)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 13"))))
        item = self.BlockTable_5.item(1, 4)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 14"))))
        item = self.BlockTable_5.item(1, 5)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 15"))))
        item = self.BlockTable_5.item(1, 6)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_5.item(1, 7)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_5.item(1, 8)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_5.item(1, 9)
        item.setText(_translate("BlueLine", "-"))
        self.BlockTable_5.setSortingEnabled(__sortingEnabled)
        self.Authority.setText(_translate("BlueLine", "Authority (Blocks)"))
        self.CommandedSpeed.setText(_translate("BlueLine", "Commanded Speed (MPH)"))
        self.SignalLights.setText(_translate("BlueLine", "Signal Lights (R\Y\G)"))
        self.SignalLights_2.setText(_translate("BlueLine", "Broken Rail"))

        if blueLine.getGatePositions()==True:
            self.label.setText(_translate("BlueLine", "Up"))
        else:
            self.label.setText(_translate("BlueLine", "Down"))

        item = self.BlockTable_8.verticalHeaderItem(1)
        item.setText(_translate("BlueLine", "1"))
        item = self.BlockTable_8.horizontalHeaderItem(0)
        item.setText(_translate("BlueLine", "0"))
        item = self.BlockTable_8.horizontalHeaderItem(1)
        item.setText(_translate("BlueLine", "1"))
        item = self.BlockTable_8.horizontalHeaderItem(2)
        item.setText(_translate("BlueLine", "2"))
        item = self.BlockTable_8.horizontalHeaderItem(3)
        item.setText(_translate("BlueLine", "3"))
        item = self.BlockTable_8.horizontalHeaderItem(4)
        item.setText(_translate("BlueLine", "4"))
        item = self.BlockTable_8.horizontalHeaderItem(5)
        item.setText(_translate("BlueLine", "5"))
        item = self.BlockTable_8.horizontalHeaderItem(6)
        item.setText(_translate("BlueLine", "6"))
        item = self.BlockTable_8.horizontalHeaderItem(7)
        item.setText(_translate("BlueLine", "7"))
        item = self.BlockTable_8.horizontalHeaderItem(8)
        item.setText(_translate("BlueLine", "8"))
        item = self.BlockTable_8.horizontalHeaderItem(9)
        item.setText(_translate("BlueLine", "9"))
        __sortingEnabled = self.BlockTable_8.isSortingEnabled()
        self.BlockTable_8.setSortingEnabled(False)
        item = self.BlockTable_8.item(0, 0)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_8.item(0, 1)
        item.setText(_translate("BlueLine", str(blueLine.getAuthority("Block 1"))))
        item = self.BlockTable_8.item(0, 2)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 2"))))
        item = self.BlockTable_8.item(0, 3)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 3"))))
        item = self.BlockTable_8.item(0, 4)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 4"))))
        item = self.BlockTable_8.item(0, 5)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 5"))))
        item = self.BlockTable_8.item(0, 6)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 6"))))
        item = self.BlockTable_8.item(0, 7)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 7"))))
        item = self.BlockTable_8.item(0, 8)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 8"))))
        item = self.BlockTable_8.item(0, 9)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 9"))))
        item = self.BlockTable_8.item(1, 0)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 10"))))
        item = self.BlockTable_8.item(1, 1)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 11"))))
        item = self.BlockTable_8.item(1, 2)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 12"))))
        item = self.BlockTable_8.item(1, 3)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 13"))))
        item = self.BlockTable_8.item(1, 4)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 14"))))
        item = self.BlockTable_8.item(1, 5)
        item.setText(_translate("BlueLine", str(blueLine.getCommandedSpeed("Block 15"))))
        item = self.BlockTable_8.item(1, 6)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_8.item(1, 7)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_8.item(1, 8)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_8.item(1, 9)
        item.setText(_translate("BlueLine", "-"))
        self.BlockTable_8.setSortingEnabled(__sortingEnabled)
        ########OCCUPANCY############
        item = self.BlockTable_9.verticalHeaderItem(1)
        item.setText(_translate("BlueLine", "1"))
        item = self.BlockTable_9.horizontalHeaderItem(0)
        item.setText(_translate("BlueLine", "0"))
        item = self.BlockTable_9.horizontalHeaderItem(1)
        item.setText(_translate("BlueLine", "1"))
        item = self.BlockTable_9.horizontalHeaderItem(2)
        item.setText(_translate("BlueLine", "2"))
        item = self.BlockTable_9.horizontalHeaderItem(3)
        item.setText(_translate("BlueLine", "3"))
        item = self.BlockTable_9.horizontalHeaderItem(4)
        item.setText(_translate("BlueLine", "4"))
        item = self.BlockTable_9.horizontalHeaderItem(5)
        item.setText(_translate("BlueLine", "5"))
        item = self.BlockTable_9.horizontalHeaderItem(6)
        item.setText(_translate("BlueLine", "6"))
        item = self.BlockTable_9.horizontalHeaderItem(7)
        item.setText(_translate("BlueLine", "7"))
        item = self.BlockTable_9.horizontalHeaderItem(8)
        item.setText(_translate("BlueLine", "8"))
        item = self.BlockTable_9.horizontalHeaderItem(9)
        item.setText(_translate("BlueLine", "9"))
        __sortingEnabled = self.BlockTable_9.isSortingEnabled()
        self.BlockTable_9.setSortingEnabled(False)
        item = self.BlockTable_9.item(0, 0)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_9.item(0, 1)

        if blueLine.getOccupancy("Block 1")==True:
            item.setText(_translate("BlueLine", "X"))
        else:
            item.setText(_translate("BlueLine",""))

        item = self.BlockTable_9.item(0, 2)

        if blueLine.getOccupancy("Block 2")==True:
            item.setText(_translate("BlueLine", "X"))
        else:
            item.setText(_translate("BlueLine",""))

        item = self.BlockTable_9.item(0, 3)
        
        if blueLine.getOccupancy("Block 3")==True:
            item.setText(_translate("BlueLine", "X"))
        else:
            item.setText(_translate("BlueLine",""))

        item = self.BlockTable_9.item(0, 4)

        if blueLine.getOccupancy("Block 4")==True:
            item.setText(_translate("BlueLine", "X"))
        else:
            item.setText(_translate("BlueLine",""))
        
        item = self.BlockTable_9.item(0, 5)
        
        if blueLine.getOccupancy("Block 5")==True:
            item.setText(_translate("BlueLine", "X"))
        else:
            item.setText(_translate("BlueLine",""))

        item = self.BlockTable_9.item(0, 6)

        if blueLine.getOccupancy("Block 6")==True:
            item.setText(_translate("BlueLine", "X"))
        else:
            item.setText(_translate("BlueLine",""))        

        item = self.BlockTable_9.item(0, 7)
        
        if blueLine.getOccupancy("Block 7")==True:
            item.setText(_translate("BlueLine", "X"))
        else:
            item.setText(_translate("BlueLine",""))

        item = self.BlockTable_9.item(0, 8)
        
        if blueLine.getOccupancy("Block 8")==True:
            item.setText(_translate("BlueLine", "X"))
        else:
            item.setText(_translate("BlueLine",""))
        
        item = self.BlockTable_9.item(0, 9)
        
        if blueLine.getOccupancy("Block 9")==True:
            item.setText(_translate("BlueLine", "X"))
        else:
            item.setText(_translate("BlueLine",""))

        item = self.BlockTable_9.item(1, 0)
        
        if blueLine.getOccupancy("Block 10")==True:
            item.setText(_translate("BlueLine", "X"))
        else:
            item.setText(_translate("BlueLine",""))

        item = self.BlockTable_9.item(1, 1)

        if blueLine.getOccupancy("Block 11")==True:
            item.setText(_translate("BlueLine", "X"))
        else:
            item.setText(_translate("BlueLine",""))

        item = self.BlockTable_9.item(1, 2)
        
        if blueLine.getOccupancy("Block 12")==True:
            item.setText(_translate("BlueLine", "X"))
        else:
            item.setText(_translate("BlueLine",""))

        item = self.BlockTable_9.item(1, 3)
        
        if blueLine.getOccupancy("Block 13")==True:
            item.setText(_translate("BlueLine", "X"))
        else:
            item.setText(_translate("BlueLine",""))

        item = self.BlockTable_9.item(1, 4)
        
        if blueLine.getOccupancy("Block 14")==True:
            item.setText(_translate("BlueLine", "X"))
        else:
            item.setText(_translate("BlueLine",""))

        item = self.BlockTable_9.item(1, 5)
        
        if blueLine.getOccupancy("Block 15")==True:
            item.setText(_translate("BlueLine", "X"))
        else:
            item.setText(_translate("BlueLine",""))

        item = self.BlockTable_9.item(1, 6)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_9.item(1, 7)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_9.item(1, 8)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_9.item(1, 9)
        item.setText(_translate("BlueLine", "-"))
        self.BlockTable_9.setSortingEnabled(__sortingEnabled)
        ########Signals##########
        item = self.BlockTable_10.verticalHeaderItem(1)
        item.setText(_translate("BlueLine", "1"))
        item = self.BlockTable_10.horizontalHeaderItem(0)
        item.setText(_translate("BlueLine", "0"))
        item = self.BlockTable_10.horizontalHeaderItem(1)
        item.setText(_translate("BlueLine", "1"))
        item = self.BlockTable_10.horizontalHeaderItem(2)
        item.setText(_translate("BlueLine", "2"))
        item = self.BlockTable_10.horizontalHeaderItem(3)
        item.setText(_translate("BlueLine", "3"))
        item = self.BlockTable_10.horizontalHeaderItem(4)
        item.setText(_translate("BlueLine", "4"))
        item = self.BlockTable_10.horizontalHeaderItem(5)
        item.setText(_translate("BlueLine", "5"))
        item = self.BlockTable_10.horizontalHeaderItem(6)
        item.setText(_translate("BlueLine", "6"))
        item = self.BlockTable_10.horizontalHeaderItem(7)
        item.setText(_translate("BlueLine", "7"))
        item = self.BlockTable_10.horizontalHeaderItem(8)
        item.setText(_translate("BlueLine", "8"))
        item = self.BlockTable_10.horizontalHeaderItem(9)
        item.setText(_translate("BlueLine", "9"))
        __sortingEnabled = self.BlockTable_10.isSortingEnabled()
        self.BlockTable_10.setSortingEnabled(False)
        item = self.BlockTable_10.item(0, 0)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_10.item(0, 1)
        item.setText(_translate("BlueLine", blueLine.getSignalLights("Block 1")))
        item = self.BlockTable_10.item(0, 2)
        item.setText(_translate("BlueLine", blueLine.getSignalLights("Block 2")))
        item = self.BlockTable_10.item(0, 3)
        item.setText(_translate("BlueLine", blueLine.getSignalLights("Block 3")))
        item = self.BlockTable_10.item(0, 4)
        item.setText(_translate("BlueLine", blueLine.getSignalLights("Block 4")))
        item = self.BlockTable_10.item(0, 5)
        item.setText(_translate("BlueLine", blueLine.getSignalLights("Block 5")))
        item = self.BlockTable_10.item(0, 6)
        item.setText(_translate("BlueLine", blueLine.getSignalLights("Block 6")))
        item = self.BlockTable_10.item(0, 7)
        item.setText(_translate("BlueLine", blueLine.getSignalLights("Block 7")))
        item = self.BlockTable_10.item(0, 8)
        item.setText(_translate("BlueLine", blueLine.getSignalLights("Block 8")))
        item = self.BlockTable_10.item(0, 9)
        item.setText(_translate("BlueLine", blueLine.getSignalLights("Block 9")))
        item = self.BlockTable_10.item(1, 0)
        item.setText(_translate("BlueLine", blueLine.getSignalLights("Block 10")))
        item = self.BlockTable_10.item(1, 1)
        item.setText(_translate("BlueLine", blueLine.getSignalLights("Block 11")))
        item = self.BlockTable_10.item(1, 2)
        item.setText(_translate("BlueLine", blueLine.getSignalLights("Block 12")))
        item = self.BlockTable_10.item(1, 3)
        item.setText(_translate("BlueLine", blueLine.getSignalLights("Block 13")))
        item = self.BlockTable_10.item(1, 4)
        item.setText(_translate("BlueLine", blueLine.getSignalLights("Block 14")))
        item = self.BlockTable_10.item(1, 5)
        item.setText(_translate("BlueLine", blueLine.getSignalLights("Block 15")))
        item = self.BlockTable_10.item(1, 6)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_10.item(1, 7)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_10.item(1, 8)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_10.item(1, 9)
        item.setText(_translate("BlueLine", "-"))
        self.BlockTable_10.setSortingEnabled(__sortingEnabled)
        #######     BROKEN RAIL ##########
        item = self.BlockTable_11.verticalHeaderItem(1)
        item.setText(_translate("BlueLine", "1"))
        item = self.BlockTable_11.horizontalHeaderItem(0)
        item.setText(_translate("BlueLine", "0"))
        item = self.BlockTable_11.horizontalHeaderItem(1)
        item.setText(_translate("BlueLine", "1"))
        item = self.BlockTable_11.horizontalHeaderItem(2)
        item.setText(_translate("BlueLine", "2"))
        item = self.BlockTable_11.horizontalHeaderItem(3)
        item.setText(_translate("BlueLine", "3"))
        item = self.BlockTable_11.horizontalHeaderItem(4)
        item.setText(_translate("BlueLine", "4"))
        item = self.BlockTable_11.horizontalHeaderItem(5)
        item.setText(_translate("BlueLine", "5"))
        item = self.BlockTable_11.horizontalHeaderItem(6)
        item.setText(_translate("BlueLine", "6"))
        item = self.BlockTable_11.horizontalHeaderItem(7)
        item.setText(_translate("BlueLine", "7"))
        item = self.BlockTable_11.horizontalHeaderItem(8)
        item.setText(_translate("BlueLine", "8"))
        item = self.BlockTable_11.horizontalHeaderItem(9)
        item.setText(_translate("BlueLine", "9"))
        __sortingEnabled = self.BlockTable_11.isSortingEnabled()
        self.BlockTable_11.setSortingEnabled(False)
        item = self.BlockTable_11.item(0, 0)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_11.item(0, 1)

        if blueLine.getBrokenRail("Block 1")==True:
            item.setText(_translate("BlueLine", "BREAK"))
        else:
            item.setText(_translate("BlueLine", ""))
    
        item = self.BlockTable_11.item(0, 2)
        
        if blueLine.getBrokenRail("Block 2")==True:
            item.setText(_translate("BlueLine", "BREAK"))
        else:
            item.setText(_translate("BlueLine", ""))

        item = self.BlockTable_11.item(0, 3)

        if blueLine.getBrokenRail("Block 3")==True:
            item.setText(_translate("BlueLine", "BREAK"))
        else:
            item.setText(_translate("BlueLine", ""))

        item = self.BlockTable_11.item(0, 4)

        if blueLine.getBrokenRail("Block 4")==True:
            item.setText(_translate("BlueLine", "BREAK"))
        else:
            item.setText(_translate("BlueLine", ""))

        item = self.BlockTable_11.item(0, 5)

        if blueLine.getBrokenRail("Block 5")==True:
            item.setText(_translate("BlueLine", "BREAK"))
        else:
            item.setText(_translate("BlueLine", ""))
       
        item = self.BlockTable_11.item(0, 6)
       
        if blueLine.getBrokenRail("Block 6") == True:
            item.setText(_translate("BlueLine", "BREAK"))
        else:
            item.setText(_translate("BlueLine", ""))

        item = self.BlockTable_11.item(0, 7)

        if blueLine.getBrokenRail("Block 7") == True:
            item.setText(_translate("BlueLine", "BREAK"))
        else:
            item.setText(_translate("BlueLine", ""))

        item = self.BlockTable_11.item(0, 8)

        if blueLine.getBrokenRail("Block 8") == True:
            item.setText(_translate("BlueLine", "BREAK"))
        else:
            item.setText(_translate("BlueLine", ""))
        
        item = self.BlockTable_11.item(0, 9)
        
        if blueLine.getBrokenRail("Block 9")==True:
            item.setText(_translate("BlueLine", "BREAK"))
        else:
            item.setText(_translate("BlueLine", ""))

        item = self.BlockTable_11.item(1, 0)
        
        if blueLine.getBrokenRail("Block 10")==True:
            item.setText(_translate("BlueLine", "BREAK"))
        else:
            item.setText(_translate("BlueLine", ""))

        item = self.BlockTable_11.item(1, 1)
        
        if blueLine.getBrokenRail("Block 11")==True:
            item.setText(_translate("BlueLine", "BREAK"))
        else:
            item.setText(_translate("BlueLine", ""))

        item = self.BlockTable_11.item(1, 2)
        
        if blueLine.getBrokenRail("Block 12")==True:
            item.setText(_translate("BlueLine", "BREAK"))
        else:
            item.setText(_translate("BlueLine", ""))        

        item = self.BlockTable_11.item(1, 3)
        
        if blueLine.getBrokenRail("Block 13")==True:
            item.setText(_translate("BlueLine", "BREAK"))
        else:
            item.setText(_translate("BlueLine", ""))

        item = self.BlockTable_11.item(1, 4)

        if blueLine.getBrokenRail("Block 14")==True:
            item.setText(_translate("BlueLine", "BREAK"))
        else:
            item.setText(_translate("BlueLine", ""))       

        item = self.BlockTable_11.item(1, 5)
        
        if blueLine.getBrokenRail("Block 15")==True:
            item.setText(_translate("BlueLine", "BREAK"))
        else:
            item.setText(_translate("BlueLine", ""))

        item = self.BlockTable_11.item(1, 6)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_11.item(1, 7)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_11.item(1, 8)
        item.setText(_translate("BlueLine", "-"))
        item = self.BlockTable_11.item(1, 9)
        item.setText(_translate("BlueLine", "-"))
        self.BlockTable_11.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BlueLine = QtWidgets.QMainWindow()
    ui = UI_BlueLine()
    ui.setupUi(BlueLine)
    BlueLine.show()
    sys.exit(app.exec())
