from PyQt6 import QtCore, QtGui, QtWidgets
#import WaysideController.py

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 598)
        MainWindow.setStyleSheet("QWidget{\n"
"\n"
"background-color:#adadadad\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(400, 200, 151, 301))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(100, 210, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 470, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")

        self.Visual_Up = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Visual_Up.setGeometry(QtCore.QRect(180, 480, 51, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Visual_Up.setFont(font)
        self.Visual_Up.setCheckable(False)
        self.Visual_Up.setObjectName("Visual_Up")

        self.Visual_down = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Visual_down.setGeometry(QtCore.QRect(250, 480, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Visual_down.setFont(font)
        self.Visual_down.setCheckable(False)
        self.Visual_down.setObjectName("Visual_down")

        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(480, 520, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        #Signal buttons
        self.Visual_red = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Visual_red.setGeometry(QtCore.QRect(610, 500, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Visual_red.setFont(font)
        self.Visual_red.setCheckable(False)
        self.Visual_red.setObjectName("Visual_red")

        self.visual_yellow = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.visual_yellow.setGeometry(QtCore.QRect(610, 530, 82, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.visual_yellow.setFont(font)
        self.visual_yellow.setCheckable(False)
        self.visual_yellow.setObjectName("visual_yellow")

        self.visual_green = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.visual_green.setGeometry(QtCore.QRect(610, 560, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.visual_green.setFont(font)
        self.visual_green.setCheckable(False)
        self.visual_green.setObjectName("visual_green")

        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(580, 210, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(650, 210, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(580, 250, 21, 17))
        self.radioButton.setText("")
        self.radioButton.setCheckable(False)
        self.radioButton.setObjectName("radioButton")

        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(650, 250, 21, 17))
        self.radioButton_2.setText("")
        self.radioButton_2.setCheckable(False)
        self.radioButton_2.setObjectName("radioButton_2")

        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(580, 290, 21, 17))
        self.radioButton_3.setText("")
        self.radioButton_3.setCheckable(False)
        self.radioButton_3.setObjectName("radioButton_3")

        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(650, 290, 21, 17))
        self.radioButton_4.setText("")
        self.radioButton_4.setCheckable(False)
        self.radioButton_4.setObjectName("radioButton_4")

        self.radioButton_5 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(580, 320, 21, 17))
        self.radioButton_5.setText("")
        self.radioButton_5.setCheckable(False)
        self.radioButton_5.setObjectName("radioButton_5")

        self.radioButton_6 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(650, 320, 21, 17))
        self.radioButton_6.setText("")
        self.radioButton_6.setCheckable(False)
        self.radioButton_6.setObjectName("radioButton_6")

        self.radioButton_7 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_7.setGeometry(QtCore.QRect(580, 360, 21, 17))
        self.radioButton_7.setText("")
        self.radioButton_7.setCheckable(False)
        self.radioButton_7.setObjectName("radioButton_7")

        self.radioButton_8 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(650, 360, 21, 17))
        self.radioButton_8.setText("")
        self.radioButton_8.setCheckable(False)
        self.radioButton_8.setObjectName("radioButton_8")

        self.radioButton_9 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_9.setGeometry(QtCore.QRect(580, 400, 21, 17))
        self.radioButton_9.setText("")
        self.radioButton_9.setCheckable(False)
        self.radioButton_9.setObjectName("radioButton_9")

        self.radioButton_10 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_10.setGeometry(QtCore.QRect(650, 400, 21, 17))
        self.radioButton_10.setText("")
        self.radioButton_10.setCheckable(False)
        self.radioButton_10.setObjectName("radioButton_10")
        
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 10, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 20, 47, 13))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 50, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 90, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 130, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 160, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(0, 190, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(120, 50, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(120, 90, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(120, 130, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(120, 160, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(120, 190, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(230, 50, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(230, 90, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(230, 130, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(230, 160, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(230, 190, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(370, 120, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(370, 150, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(370, 40, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(370, 80, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(370, 180, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(590, 150, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(590, 40, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(590, 120, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(590, 180, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(590, 80, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(490, 40, 47, 13))
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(480, 40, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(480, 80, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(480, 120, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(480, 150, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(480, 180, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(40, 260, 221, 191))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(30, 540, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(120, 540, 91, 31))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(240, 550, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(350, 550, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.radioButton_11 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_11.setGeometry(QtCore.QRect(650, 430, 21, 17))
        self.radioButton_11.setText("")
        self.radioButton_11.setCheckable(False)
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_12.setGeometry(QtCore.QRect(580, 430, 21, 17))
        self.radioButton_12.setText("")
        self.radioButton_12.setCheckable(False)
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_13 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_13.setGeometry(QtCore.QRect(650, 470, 21, 17))
        self.radioButton_13.setText("")
        self.radioButton_13.setCheckable(False)
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_14.setGeometry(QtCore.QRect(580, 470, 21, 17))
        self.radioButton_14.setText("")
        self.radioButton_14.setCheckable(False)
        self.radioButton_14.setObjectName("radioButton_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "        Switches\n"
"\n"
"Block (75-Yard;Yard-75)\n"
"\n"
"Block (15-16;1-16)\n"
"\n"
"Block (27-28;27-76)\n"
"\n"
"Block (32-33;33-72)\n"
"\n"
"Block (38-39;38-71) \n"
"\n"
"Block (43-44;44-67) \n"
"\n"
"Block (52-53;52-66)"))
        self.label_13.setText(_translate("MainWindow", "Occupancy"))
        self.label_12.setText(_translate("MainWindow", "Gate Status: Block 19"))
        self.Visual_Up.setText(_translate("MainWindow", "Up"))
        self.Visual_down.setText(_translate("MainWindow", "Down"))
        self.label_11.setText(_translate("MainWindow", "Signal Light"))
        self.Visual_red.setText(_translate("MainWindow", "Red"))
        self.visual_yellow.setText(_translate("MainWindow", "Yellow"))
        self.visual_green.setText(_translate("MainWindow", "Green"))
        self.label_6.setText(_translate("MainWindow", "L"))
        self.label_7.setText(_translate("MainWindow", "R"))
        self.label.setText(_translate("MainWindow", "Commanded Speed"))
        self.label_3.setText(_translate("MainWindow", "Authority"))
        self.label_4.setText(_translate("MainWindow", "Train 1"))
        self.label_5.setText(_translate("MainWindow", "Train 2"))
        self.label_8.setText(_translate("MainWindow", "Train 3"))
        self.label_10.setText(_translate("MainWindow", "Train 4"))
        self.label_14.setText(_translate("MainWindow", "Train 5"))
        self.label_15.setText(_translate("MainWindow", "Train 1 speed change"))
        self.label_16.setText(_translate("MainWindow", "Train 2 speed change"))
        self.label_17.setText(_translate("MainWindow", "Train 3 speed change"))
        self.label_18.setText(_translate("MainWindow", "Train 4 speed change"))
        self.label_19.setText(_translate("MainWindow", "Train 5 speed change"))
        self.label_20.setText(_translate("MainWindow", "MPH"))
        self.label_21.setText(_translate("MainWindow", "MPH"))
        self.label_22.setText(_translate("MainWindow", "MPH"))
        self.label_23.setText(_translate("MainWindow", "MPH"))
        self.label_24.setText(_translate("MainWindow", "MPH"))
        self.label_25.setText(_translate("MainWindow", "Train 3"))
        self.label_26.setText(_translate("MainWindow", "Train 4"))
        self.label_27.setText(_translate("MainWindow", "Train 1"))
        self.label_28.setText(_translate("MainWindow", "Train 2"))
        self.label_29.setText(_translate("MainWindow", "Train 5"))
        self.label_30.setText(_translate("MainWindow", "Blocks"))
        self.label_31.setText(_translate("MainWindow", "Blocks"))
        self.label_32.setText(_translate("MainWindow", "Blocks"))
        self.label_33.setText(_translate("MainWindow", "Blocks"))
        self.label_34.setText(_translate("MainWindow", "Blocks"))
        self.label_36.setText(_translate("MainWindow", "Train 1 Authority please change"))
        self.label_37.setText(_translate("MainWindow", "Train 2 Authority please change"))
        self.label_38.setText(_translate("MainWindow", "Train 3 Authority please change"))
        self.label_39.setText(_translate("MainWindow", "Train 4 Authority please change"))
        self.label_40.setText(_translate("MainWindow", "Train 5 Authority please change"))
        self.label_41.setText(_translate("MainWindow", "Block texts"))
        self.label_42.setText(_translate("MainWindow", "Operational"))
        self.label_43.setText(_translate("MainWindow", "True if 1 False if 0"))
        self.label_44.setText(_translate("MainWindow", "Broken Rail"))
        self.label_45.setText(_translate("MainWindow", "Block : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
