from PyQt6.QtGui import *
from PyQt6.QtCore import *

power = pyqtSignal(float)
authority = pyqtSignal(int)
serviceBrake = pyqtSignal(bool)
emergencyBrake = pyqtSignal(bool)
leftDoors = pyqtSignal(bool)
rightDoors = pyqtSignal(bool)
internalLights = pyqtSignal(bool)
externalLights = pyqtSignal(bool)
stationLabel = pyqtSignal(str)
realTimeClock = pyqtSignal(str)
commandedSpeed = pyqtSignal(float)
passengersEntering = pyqtSignal(int)
grade = pyqtSignal(float)
elevation = pyqtSignal(float)
speedLimit = pyqtSignal(int)
accelerationLimit = pyqtSignal(float)
underground = pyqtSignal(bool)
beacon = pyqtSignal([bool, str, int])
current = pyqtSignal([float, float])
previous = pyqtSignal([float, float])
mass = pyqtSignal(float)